import random
a = random.randrange(1, 100)
b = random.randrange(1, 100)
c = random.randrange(1, 100) 
d = random.randrange(1, 100) 
e = random.randrange(1, 100) 
f = random.randrange(1, 100) 
g = random.randrange(1, 100) 
h = random.randrange(1, 100) 
i = random.randrange(1, 100) 
j = random.randrange(1, 100) 
k = random.randrange(1, 100) 
l = random.randrange(1, 100) 
m = random.randrange(1, 100) 
n = random.randrange(1, 100)
o = random.randrange(1, 100)
p = random.randrange(1, 100)
q = random.randrange(1, 100)
r = random.randrange(1, 100)
s = random.randrange(1, 100)
t = random.randrange(1, 100)
u = random.randrange(1, 100)
v = random.randrange(1, 100)
w = random.randrange(1, 100)
x = random.randrange(1, 100)
y = random.randrange(1, 100)
z = random.randrange(1, 100)
aa = random.randrange(1, 100)
bb = random.randrange(1, 100)
cc = random.randrange(1, 100)
dd = random.randrange(1, 100)

tuple_1 = (a, b, c)
tuple_2 = (d, e, f)
tuple_3 = (g, h, i)
tuple_4 = (j, k, l)
tuple_5 = (m, n, o)
tuple_6 = (p, q, r)
tuple_7 = (s, t, u)
tuple_8 = (v, w, x)
tuple_9 = (y, z, aa)
tuple_10 = (bb, cc, dd)

list = [tuple_1, tuple_2, tuple_3, tuple_4, tuple_5, tuple_6, tuple_7, tuple_8, tuple_9, tuple_10]
print(list) #here I print the list before sorting the list of tuples, just to check if the end-result is correct

list.sort(key=lambda σ: σ[-1])

print(list) #result with list of tuples in increasing order of the third element in each tuple